# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRf3iWJvwVo_-B8AVcndhvfd50Xx3p4C
"""

from fastapi import FastAPI, File, UploadFile
import torch
import torch.nn as nn
from PIL import Image
import io
import torchvision.transforms as transforms
from torchvision import transforms
from fastapi.middleware.cors import CORMiddleware

app = FastAPI(title="MNIST CNN API")

#Allow frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],

)

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# CNN Model (same as training)
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, 3, padding=1)
        self.conv2 = nn.Conv2d(16, 32, 3, padding=1)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(32 * 7 * 7, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = x.view(-1, 32 * 7 * 7)
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Load model
model = CNN().to(device)
model.load_state_dict(torch.load("mnist_weights.pth", map_location=device))
model.eval()

# Image transform
transform = transforms.Compose([
    transforms.Grayscale(),   # ensure 1 channel
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# Home route
@app.get("/")
def home():
    return {"message": "MNIST CNN API is running"}

# Prediction route
@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    image_data = await file.read()
    image = Image.open(io.BytesIO(image_data))

    # Preprocess
    image = transform(image).unsqueeze(0).to(device)

    # Predict
    with torch.no_grad():
        output = model(image)
        prediction = torch.argmax(output, 1).item()

    return {"prediction": prediction}
